modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''
# 伤害数据全部由服务端采集，客户端单独装拿不到任何统计，所以要求两端都装且版本一致
displayTest="MATCH_VERSION"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
